### ISSUE TITLE
Analaysis of IsolatedNetwork vs TrustDomain

### ISSUE THREAD

**Issue by benhepworth** [camaraproject/NetworkAccessManagement#36]
**Problem description**
Compare existing IsolatedNetwork schema with TrustDomain schema from CableLabs proposal

**Additional context**
Discuss and come to an agreement on new schema moving forward.

[zto-openapi-yaml.txt](https://github.com/user-attachments/files/19392719/zto-openapi-yaml.txt)

**Comment by clundie-CL** [comment]
The existing NAM `Network` schema that is returned by GET /isolated-networks/{netId}

```yaml
  {
    "id": "wifi-1",
    "description": "my network",
    "accessDetail": {
        "accessType": "Wi-Fi",
        "ssid": "my-ssid",
        "securityMode": {
          "password": "my-password",
          "securityModeType": "WPA3-Personal"
        }
    },
    "expiration": "2023-07-03T14:27:08.312+02:00",
    "createdAt": "2023-07-03T14:27:08.312+02:00",
    "createdBy": "user-1",
    "modifiedAt": "2023-07-03T14:27:08.312+02:00",
    "modifiedBy": "user-2",
    "version": "1234ABCD"
}
```

> Note: accessDetail is a nested discriminator and can take on several response formats. 

The existing ZTO "TrustDomainBase` schema that is returned by GET

```yaml
{
  "name": "string",
  "enabled": true,
  "expires": "2019-08-24T14:15:22Z",
  "options": {
      "maxDevices": 0,
      "maxUpstreamKbps": 0,
      "maxDownstreamKbps": 0,
      "ssid": "string",
      "domainCredential": {
          "WPA2_PASSPHRASE": "example-passphrase",
          "WPA3_PASSWORD": "another-example-password"
    }
  },
  "uuid": "string",
  "ipv4subnet": "string",
  "ipv6subnet": "string"
}
```
